/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'ghost-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.android-arm64.node')
          } else {
            nativeBinding = require('ghost-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'ghost-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('ghost-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'ghost-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('ghost-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'ghost-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('ghost-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'ghost-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('ghost-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'ghost-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./ghost-native.darwin-universal.node')
      } else {
        nativeBinding = require('ghost-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'ghost-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.darwin-x64.node')
          } else {
            nativeBinding = require('ghost-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'ghost-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.darwin-arm64.node')
          } else {
            nativeBinding = require('ghost-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'ghost-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./ghost-native.freebsd-x64.node')
      } else {
        nativeBinding = require('ghost-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('ghost-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('ghost-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('ghost-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('ghost-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('ghost-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('ghost-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('ghost-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'ghost-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./ghost-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('ghost-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'ghost-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./ghost-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('ghost-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { isParakeetDownloaded, getParakeetModelInfo, getParakeetLanguages, getParakeetDownloadProgress, downloadParakeetModel, initParakeet, isParakeetReady, transcribeAudioBuffer, transcribeAudioBufferWithTimestamps, deleteParakeetModel, getParakeetModelPath, shutdownParakeet, getLlmModelInfo, getLlmInitProgress, isLlmReady, isLlmDownloaded, initLlm, initLlmSync, shutdownLlm, deleteLlmModel, llmGenerate, llmChat, llmChatStream, getActiveWindows, checkAccessibilityPermission, requestAccessibilityPermission, checkScreenRecordingPermission, requestScreenRecordingPermission, triggerScreenRecordingPrompt, getBrowserUrl, startAudioCapture, stopAudioCapture, getAudioLevel, isCapturing, getCaptureDuration, isMicrophoneInUse, getAudioChunks, hasAudioChunks } = nativeBinding

module.exports.isParakeetDownloaded = isParakeetDownloaded
module.exports.getParakeetModelInfo = getParakeetModelInfo
module.exports.getParakeetLanguages = getParakeetLanguages
module.exports.getParakeetDownloadProgress = getParakeetDownloadProgress
module.exports.downloadParakeetModel = downloadParakeetModel
module.exports.initParakeet = initParakeet
module.exports.isParakeetReady = isParakeetReady
module.exports.transcribeAudioBuffer = transcribeAudioBuffer
module.exports.transcribeAudioBufferWithTimestamps = transcribeAudioBufferWithTimestamps
module.exports.deleteParakeetModel = deleteParakeetModel
module.exports.getParakeetModelPath = getParakeetModelPath
module.exports.shutdownParakeet = shutdownParakeet
module.exports.getLlmModelInfo = getLlmModelInfo
module.exports.getLlmInitProgress = getLlmInitProgress
module.exports.isLlmReady = isLlmReady
module.exports.isLlmDownloaded = isLlmDownloaded
module.exports.initLlm = initLlm
module.exports.initLlmSync = initLlmSync
module.exports.shutdownLlm = shutdownLlm
module.exports.deleteLlmModel = deleteLlmModel
module.exports.llmGenerate = llmGenerate
module.exports.llmChat = llmChat
module.exports.llmChatStream = llmChatStream
module.exports.getActiveWindows = getActiveWindows
module.exports.checkAccessibilityPermission = checkAccessibilityPermission
module.exports.requestAccessibilityPermission = requestAccessibilityPermission
module.exports.checkScreenRecordingPermission = checkScreenRecordingPermission
module.exports.requestScreenRecordingPermission = requestScreenRecordingPermission
module.exports.triggerScreenRecordingPrompt = triggerScreenRecordingPrompt
module.exports.getBrowserUrl = getBrowserUrl
module.exports.startAudioCapture = startAudioCapture
module.exports.stopAudioCapture = stopAudioCapture
module.exports.getAudioLevel = getAudioLevel
module.exports.isCapturing = isCapturing
module.exports.getCaptureDuration = getCaptureDuration
module.exports.isMicrophoneInUse = isMicrophoneInUse
module.exports.getAudioChunks = getAudioChunks
module.exports.hasAudioChunks = hasAudioChunks
