/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Window information returned from native APIs */
export interface WindowInfo {
  pid: number
  windowId: number
  ownerName: string
  title: string
  bundleId?: string
}
/** Audio capture configuration */
export interface AudioCaptureOptions {
  sampleRate?: number
  channels?: number
  outputPath?: string
  includeMicrophone?: boolean
}
/** Get all visible windows on the system */
export declare function getActiveWindows(): Array<WindowInfo>
/** Check if accessibility permissions are granted (macOS) */
export declare function checkAccessibilityPermission(): boolean
/** Request accessibility permissions (macOS) - opens System Settings */
export declare function requestAccessibilityPermission(): boolean
/** Check if screen recording permission is granted (macOS) */
export declare function checkScreenRecordingPermission(): boolean
/** Request screen recording permission (macOS) - prompts user if not granted */
export declare function requestScreenRecordingPermission(): boolean
/**
 * Trigger ScreenCaptureKit to add app to Screen Recording permissions list
 * This ensures the app appears in System Settings for the user to enable
 */
export declare function triggerScreenRecordingPrompt(): void
/** Get the URL from a browser window (requires accessibility permission) */
export declare function getBrowserUrl(pid: number): string | null
/** Start capturing audio from a specific process */
export declare function startAudioCapture(pid: number, options?: AudioCaptureOptions | undefined | null): Promise<void>
/** Stop capturing audio and return the path to the recorded file */
export declare function stopAudioCapture(): Promise<string>
/** Get current audio level (0.0 - 1.0) */
export declare function getAudioLevel(): number
/** Check if currently capturing */
export declare function isCapturing(): boolean
/** Get capture duration in milliseconds */
export declare function getCaptureDuration(): number
/**
 * Check if the microphone is currently being used by any application
 * This is the definitive way to know if a meeting is still active
 */
export declare function isMicrophoneInUse(): boolean
/**
 * Get queued stereo audio chunks for streaming to Deepgram
 * Returns Vec of stereo 16-bit PCM chunks (interleaved L=system, R=mic)
 * Each chunk is ~100ms of audio at 16kHz
 */
export declare function getAudioChunks(): Array<Buffer>
/** Check if there are audio chunks ready for streaming */
export declare function hasAudioChunks(): boolean
